# Generated by Django 2.0 on 2018-04-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.CharField(default='', max_length=20, verbose_name='教学职称'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='years_old',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
    ]
