"""
Django settings for mymooc project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

sys.path.insert(0,os.path.join(BASE_DIR,'apps'))
sys.path.insert(0,os.path.join(BASE_DIR,'extra_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's!a)w^04x_t$v&8wk!@fbuii=y690euvw%8kgp_d16&5^n#f4c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False #

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'user.apps.UserConfig',        #
    'course.apps.CourseConfig',
    'organization.apps.OrganizationConfig',
    'operation.apps.OperationConfig',

    'xadmin',
    'crispy_forms',

    'captcha', #验证码app
    'pure_pagination',#分页功能app
]

AUTH_USER_MODEL = 'user.UserProfile'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mymooc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/html')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                #添加图片处理器,为了在课程列表中前面加上MEDIA_URL
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'mymooc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
        'default': {

        'ENGINE': 'django.db.backends.mysql',

        'NAME': 'mymooc',    #你的数据库名称

        'USER': 'wei',   #你的数据库用户名

        'PASSWORD': '110811', #你的数据库密码

        'HOST': '', #你的数据库主机，留空默认为localhost

        'PORT': '3306', #你的数据库端口
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

#Django 自动管理的静态文件，当denug 为false时，将失效
STATIC_URL = '/static/'
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR,'static'),
# )

#一旦debug为false Django将不会代替管理静态文件，所以这里设置一个url处理静态文件
STATIC_ROOT =  os.path.join(BASE_DIR,'static')



#添加内容------------------------------
AUTHENTICATION_BACKENDS = (
    'user.views.CustomBackend',
)

EMAIL_HOST = "smtp.qq.com" #SMTP服务器主机
EMAIL_PORT = 25
EMAIL_HOST_USER = "592190443@qq.com" #邮箱地址
EMAIL_HOST_PASSWORD = "mdiynnlqbnmmbbhg"    # 授权密码
EMAIL_USE_TLS= True
EMAIL_FROM = "592190443@qq.com"            # 邮箱地址


#资源图片文件配置
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR,'media')


#分页功能设置
PAGINATION_SETTINGS = {
    'MARGIN_PAGES_DISPLAYED': 2, #前 后2页
    'PAGE_RANGE_DISPLAYED':10, #中间10页
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}

