# Generated by Django 2.0 on 2018-04-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180426_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
