# Generated by Django 2.0 on 2018-04-29 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_banner_is_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='is_banner',
        ),
    ]
