# Generated by Django 2.0 on 2018-04-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_loginbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginbanner',
            options={'verbose_name': '登录页面轮播图', 'verbose_name_plural': '登录页面轮播图'},
        ),
    ]
