# Generated by Django 2.0 on 2018-04-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learn_what',
            field=models.CharField(default='', max_length=200, verbose_name='能学到什么'),
        ),
        migrations.AddField(
            model_name='course',
            name='need_know',
            field=models.CharField(default='', max_length=200, verbose_name='课程须知'),
        ),
    ]
