# Generated by Django 2.0 on 2018-04-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '课程轮播图',
                'verbose_name_plural': '课程轮播图',
                'proxy': True,
                'indexes': [],
            },
            bases=('course.course',),
        ),
    ]
